# lightning.pytorch==2.5.2
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: workdir/diffae_starmen
      name: condition_diffae
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  callbacks: null
  fast_dev_run: false
  max_epochs: 500
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 10
  num_sanity_val_steps: 1
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null
model:
  class_path: src.ldae.CondDDPM
  init_args:
    spartial_dim: 2
    enc_args:
      backbone_args:
        net_class_path: torchvision.models.resnet50
        weights: torchvision.models.ResNet50_Weights.DEFAULT
        freeze_perc: 0.0
        grayscale: true
      emb_chans: 512
      seq_len: 128
    unet_args:
      input_channel: 1
      base_channel: 32
      channel_multiplier:
      - 1
      - 2
      - 3
      num_residual_blocks_of_a_block: 1
      attention_resolutions:
      - 2
      - 4
      num_heads: 1
      head_channel: -1
      use_new_attention_order: false
      dropout: 0.0
      dims: 2
      use_scale_shift_norm: true
    vae_args: null
    vae_path: null
    timesteps_args:
      timesteps: 1000
      betas_type: linear
    lr: 2.5e-05
    mode: representation-learning
    pretrained_path: null
    ema_decay: 0.999
    ema_update_after_step: 10
    log_img_every_epoch: 10
    test_ddim_style: ddim100
data:
  data_dir: data/starmen/output_random_noacc
  train_ds:
    data_dir: data/starmen/output_random_noacc
    split: train
    nb_subject: null
    save_data: false
    workdir: workdir
  val_ds:
    data_dir: data/starmen/output_random_noacc
    split: val
    nb_subject: null
    save_data: false
    workdir: workdir
  test_ds: null
  batch_size:
    train: 2
    val: 2
  num_workers: 5
  shuffle:
    train: true
    val: false
early_stopping:
  monitor: train_loss
  min_delta: 0.0
  patience: 100
  verbose: true
  mode: min
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: false
model_checkpoint:
  dirpath: workdir/diffae_starmen/condition_diffae/checkpoints/
  filename: best
  monitor: val_loss
  verbose: false
  save_last: true
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
  enable_version_counter: true
optimizer: null
lr_scheduler: null
ckpt_path: null
